### ISSUE TITLE
Problems with history scroll

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#8] opened 2021-01-26 21:55 UTC
@alt-romes @AMPAlves Im currently looking at the code @AMPAlves pushed and I saw that my compiler (GCC) is giving me some warnings and the program crashes if I press the arrow keys too often.

If this bug is fixed I will take a look at splitting `main.c`

The compiler warnings can be resolved if void `add_to_searchhistory(char* in);` is added to the top of `main.c`.

I want to ask if it is beneficial to have 2 different historys implemented.
In my opinion we should make the current one comatible with history. This will remove redundant code and wont slow us down in future development.
If you have a different opinion on this, please share yours.

The redundant code Im referring to in line 464 to 472
```
void add_to_history(char* in) {
    history.records[history.size] = malloc(MAX_IN);
    strcpy(history.records[history.size++], *in == '\0' ? "0" : in);
}

void add_to_searchhistory(char* in) {
    searchHistory.inputs[searchHistory.size] = malloc(MAX_IN);
    strcpy(searchHistory.inputs[searchHistory.size++], in);
}
```

Please take a look at all the things I mentioned.

For the future I suggest making a pull request first beause there we can review the code properly.

Thanks,
DevManu-de

**Comment by alt-romes** [comment] 2021-01-26 22:11
Hello!

Just a small correction: We haven't released a new version yet, we still need to test and work with it more before releasing.
Committing to a new branch would probably be better than pushing directly to master. We'll try to coordinate it like that next time.

You're right about the redundancy, I'll ask him to refactor that :)

The bug was caused by a last refactor we did before pushing, but we've fixed it already

I'll reply here again after committing, if you still want to split `main.c` you can do it then.

Besides this, I'm not sure of other features we're thinking about implementing, if you run into a nice idea let us know

Thank you,
romes

**Comment by alt-romes** [comment] 2021-01-26 22:17
I edited the previous comment, please read the updated version 👍

**Comment by alt-romes** [comment] 2021-01-26 23:00
@DevManu-de 

From what I tested the problems with the scrolling history are now fixed - and refactored

Let me know if you find more issues with it

Thank you,
~romes

**Closed** 2021-01-27 19:45 UTC
